name = "AllanDeviations"
uuid = "3997ae70-a3ff-11e8-15d8-f1cc36d21cef"
authors = ["Julien Kluge <Julien.Kluge@gmail.com>"]
version = "0.1.0"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Pkg"]
